mysql:
  host: "localhost"
  port: 3306
  database: "database"
  username: "username"
  password: "password"

decimal-points: 1
currency-name: "Gems"
starting-balance: 0
command-name: "gems"
placeholder-game: "gems"